package com.example.bahar.ivt.Activities.Sources;

import com.example.bahar.ivt.R;

import java.util.ArrayList;

/**
 * Created by Bahar on 11/5/2018.
 */
public class DictionaryData {

    public static ArrayList<DictionaryEntry> wordsList = new ArrayList<>();



    public static void initDictionary() {

        wordsList.add(new DictionaryEntry(1, "eclipse", "/ɪˈklɪps/", "1.(noun) An obscuring of the light from one celestial body by the passage of another between it and the observer or between it and its source of illumination.\n2.(verb) Obscure or block out (light).", "synonyms:\tblotting out, blocking, covering, obscuring, hiding, concealing, veiling, shrouding, darkening; occultation\n", "noun : \"an eclipse of the sun\"\nverb :\"a sea of blue sky violently eclipsed by showers\"", "معنی : خسوف، کسوف", "کد واژه : کلیپس", "مثال : این دختر های امروزی با این <font color='black'> کلیپس </font> هاشون باعث <font color='red'>خسوف و کسوف</font>  میشن !", R.drawable.eclipse, new TestEntry("covering", "collapsing", "blending", "eroding"), "covering"));
        wordsList.add(new DictionaryEntry(1, "collapse", "/kəˈlaps/", "1.(noun)(of a structure) fall down or in; give way.\n 2.(of a person) fall down and become unconscious, typically through illness or injury.\nverb: an instance of a structure falling down or in.", "synonyms:\tcave in, fall in, subside, fall down, give (way), crumple, buckle, sag, slump, faint, pass out, black out, lose consciousness", "\"the roof collapsed on top of me\"\n" + "\"the collapse of a railroad bridge\"", "معنی : سقوط ", "کد واژه : کرفس", "مثال : <font color='black'>کرفس ها </font>چرا <font color='red'> سقوط کردن </font> ؟", R.drawable.collapse, new TestEntry("merge", "bread", "fall down", "blade"), "fall down"));
        wordsList.add(new DictionaryEntry(1, "blend", "/blɛnd/", "1.(verb) Mix (a substance) with another substance so that they combine together.\n2.(noun) A mixture of different substances or other things.", "synonyms:\tmix, mingle, combine, put together, stir, whisk, fold in, jumble, merge", "\"blend the cornflour with a tablespoon of water\"\n\"the chutney is a blend of bananas, raisins, and ginger\"", "معنی : مخلوط کردن", "کد واژه : بلوند ", "مثال : از موي <font color='black'> بلوند </font>خوشم میاد وقتی با مشکی <font color='red'> مخلوط میشه</font>.", R.drawable.blend, new TestEntry("absorb", "complex", "fade", "mix"), "mix"));
        wordsList.add(new DictionaryEntry(1, "cure", "/kjʊə,kjɔː/", "1.(verb) Relieve (a person or animal) of the symptoms of a disease or condition.\n\t**Eliminate (a disease or condition) with medical treatment.\n\t**Solve (a problem).\n*Preserve (meat, fish, tobacco, or an animal skin) by salting, drying, or smoking.\n2.(noun) A substance or treatment that cures a disease or condition.\n\t**The process of curing rubber, plastic, or other material.", "synonyms:\theal, restore to health, rectify, remedy, preserve, smoke ", "\"he was cured of the disease\"\n\"the search for a cure for the common cold\"", "معنی : مداوا کردن", "کد واژه : کور", "مثال : امروزه خیلی از آدم های <font color='black'> کور </font> میتونند <font color='red'> مداوا بشن</font>.", R.drawable.cure, new TestEntry("agitate", "heal", "remedial", "adopt"), "heal"));
        wordsList.add(new DictionaryEntry(1,"distinguish", "/dɪˈstɪŋɡwɪʃ/", "1. Recognize or treat (someone or something) as different.\n2. Manage to discern (something barely perceptible).\n3. Make oneself worthy of respect by one's behaviour or achievements.", "synonyms:\tdifferentiate, tell apart, discriminate, separate, set apart, discern, see, perceive, attain distinction, be successful, bring fame/honour to oneself", "the child is perfectly capable of distinguishing reality from fantasy", "معنی : تشخیص دادن", "کد واژه : گویش", "مثال : بعضی وقت ها نمیشه <font color='black'> گویش </font> ها رو از هم <font color='red'> تشخیص داد</font>.", R.drawable.distinguish,new TestEntry("discriminate","cast","dominate","bond"),"discriminate" ));
        wordsList.add(new DictionaryEntry(1,"erode", "/ɪˈrəʊd/", "(of wind, water, or other natural agents) Gradually wear away (soil, rock, or land).\n", "synonyms:\twear away/down, abrade, scrape away, grind down, crumble, dissolve, weather", "\"the cliffs on this coast have been eroded by the sea\"", "معنی : فرسوده شدن", "کد واژه : ایراد", "مثال : <font color='black'> ایراد </font> آهن چیه ؟ خورده شدن و <font color='red'> فرسوده شدنه</font>!", R.drawable.erode,new TestEntry("inhabit","wear away","hone","exhibit"),"wear away" ));
        wordsList.add(new DictionaryEntry(1,"loathe", "/ləʊð/", "Feel intense dislike or disgust for.", "synonyms:\thate, detest, abhor, despise, abominate, dislike greatly, execrate", "\"she loathed him on sight\"", "معنی : متنفر بودن", "کد واژه : لوس", "مثال : من که از آدمای <font color='black'> لوس </font><font color='red'>متنفرم</font>.", R.drawable.loathe,new TestEntry("subsidy","shift","hate","impact"),"hate" ));
        wordsList.add(new DictionaryEntry(1,"lease", "/liːs/", "1.(noun) A contract by which one party conveys land, property, services, etc. to another for a specified time, usually in return for a periodic payment.\n2.(verb) Grant (property) on lease; let.", "synonyms:\tleasehold, rental agreement, hire agreement, charter, contract, rent out, rent, let, let out, hire", "\"a six-month lease on a shop\"\n\"she leased the site to a local company\"", "معنی : اجاره کردن", "کد واژه : لیز", "مثال : من این خونه با کف <font color='black'> لیزش </font> و  <font color='red'>اجاره </font> نمیکنم .", R.drawable.lease,new TestEntry("sway","impose","blade","rent"),"rent" ));
        wordsList.add(new DictionaryEntry(1,"merge", "/məːdʒ/", "1. Combine or cause to combine to form a single entity.\n2. Blend or cause to blend gradually into something else so as to become indistinguishable from it.", "synonyms:\tjoin (together), join forces, amalgamate, consolidate, mingle, blend, fuse, run/melt/fade into one another, mix", "\"the merchant bank merged with another broker\"\n\"he crouched low and endeavoured to merge into the darkness of the forest\"", "معنی : فرو رفتن", "کد واژه : مرگ", "مثال : <font color='black'> مرگ </font>عزیزان آدم و تو غم <font color='red'>فرو میبره</font>.", R.drawable.merge,new TestEntry("join","ascertain","dire","appeal"),"join" ));
        wordsList.add(new DictionaryEntry(1,"fade", "/feɪd/", "1.(verb) Gradually grow faint and disappear.\n2. The process of becoming less bright.", "synonyms:\tdim, grow dim, grow faint, grow feeble, fail", "\"the light had faded and dusk was advancing\"\n\"the sun can cause colour fade\"", "معنی : محو شدن", "کد واژه : فایده", "مثال : رابطه هایی که زود کم رنگ و <font color='red'>محمو </font>میشه <font color='black'> فایده </font>نداره.", R.drawable.fade,new TestEntry("vanish","grow faint","adopt","carve"),"grow faint" ));
        wordsList.add(new DictionaryEntry(1,"generate", "/ˈjenəˌrāt/", "Cause (something, especially an emotion or situation) to arise or come about.", "synonyms:\tcause, give rise to, lead to, result in, bring about, create, make, produce, engender", "\"changes that are likely to generate controversy\"", "معنی : تولید کردن", "کد واژه : ژنراتور!", "مثال : <font color='black'>ژنراتور</font>ها برق <font color='red'>تولید میکنند</font>.", R.drawable.generate,new TestEntry("commit","rally","lead to","plead"),"lead to" ));
        wordsList.add(new DictionaryEntry(1,"qualify", "/ˈkwäləˌfī/", "1. Be entitled to a particular benefit or privilege by fulfilling a necessary condition.\n2. Make (a statement or assertion) less absolute; add reservations to.", "synonyms:\tbe eligible for, meet the requirements for, certified, certificated, chartered, credentialed, licensed", "\"they do not qualify for compensation payments\"\n\"she felt obliged to qualify her first short answer\"", "معنی : استحقاق داشتن", "کد واژه : کوالا!", "مثال : <font color='black'>کوالا </font>ها <font color='red'>استحقاق </font>غذای با کیفیت و دارن !", R.drawable.qualify,new TestEntry("concerned","dominated","organized","certified"),"certified" ));
        wordsList.add(new DictionaryEntry(1,"handle", "/ˈhandl/", "1. Feel or manipulate with the hands.\n2. Manage (a situation or problem).", "synonyms:\thold, pick up, grasp, grip, lift, deal with, manage, tackle, take care of", "\"heavy paving slabs can be difficult to handle\"\n\"a lawyer's ability to handle a case properly\"", "معنی : کمک کردن", "کد واژه : هم دل!", "مثال : آدم های <font color='black'>هم دل </font>کمکت میکنن کارات و <font color='red'>مدیریت کنی</font>!", R.drawable.handle,new TestEntry("manage","agitate","renovate","catch up"),"manage" ));
        wordsList.add(new DictionaryEntry(1,"vanish", "/ˈvaniSH/", "Disappear suddenly and completely.", "synonyms:\tdisappear, be lost to sight/view, become invisible", "\"Mary vanished without a trace\"", "معنی : ناپدید شدن", "کد واژه : و نیش!", "مثال : <font color='black'>و نیش </font>پشه است که باید سریع<font color='red'> ناپدید شه</font>.", R.drawable.vanish ,new TestEntry("merge","grasp","disappear","loath"),"disappear"));
        wordsList.add(new DictionaryEntry(1,"vacancy", "/ˈvākənsē/", "1. An unoccupied position or job.\n2. empty space.", "synonyms:\topening, position, post, job, opportunity, place", "\"a vacancy for a shorthand typist\"\n\"Cathy stared into vacancy, seeing nothing\"", "معنی : جای خالی", "کد واژه : واکسن!", "مثال : برای <font color='black'>واکسن </font>رو دستم دیگه <font color='red'>جای خالی</font> نمونده!", R.drawable.vacancy,new TestEntry("achievement","process","local company","empty space"),"empty space"));
        wordsList.add(new DictionaryEntry(1,"perilous", "/ˈperələs/", "Full of danger or risk.", "synonyms:\tdangerous, fraught with danger, hazardous, risky, unsafe, treacherous", "\"a perilous journey south\"", "معنی : خطرناک", "کد واژه :پری لوسه!", "مثال : این <font color='black'>پری </font> خیلی <font color='black'> لوسه</font> ولی دختر<font color='red'>  خطرناکی </font>هم هست!", R.drawable.perilous,new TestEntry("dangerous","mixture","property","reserved"),"dangerous"));
        wordsList.add(new DictionaryEntry(1,"triumph", "/ˈtrīəmf/", "1. A great victory or achievement.\n2. A highly successful example of something.", "synonyms:\tvictory, win, conquest, success, tour de force, masterpiece, coup, wonder", "\"a garden built to celebrate Napoleon's many triumphs\"\n\"the marriage had been a triumph of togetherness\"", "معنی : پیروز شدن", "کد واژه : ترامپ!", "مثال : این <font color='black'> ترامپ </font>هم فکر کرده <font color='red'>پیروز شده</font>!", R.drawable.triumph,new TestEntry("disappear","win","erode","carve"),"win"));
        wordsList.add(new DictionaryEntry(1,"tricky", "/ˈtrikē/", "(of a person or act) Deceitful, crafty, or skillful.", "synonyms:\tcunning, crafty, wily, guileful, artful, devious, sly, scheming, slippery, slick, calculating, designing, sharp, shrewd, astute, canny", "\"applying eyeliner can be a tricky business\"", "معنی : حیله گر", "کد واژه : تاریک!", "مثال : این آدم شخصیت <font color='black'> تاریک</font> و <font color='red'>حیله گری</font> داره! ", R.drawable.tricky,new TestEntry("difficult","perilous","cunning","slippery"),"cunning"));
        wordsList.add(new DictionaryEntry(1,"agitate", "/ˈajəˌtāt/", "Make (someone) troubled or nervous.", "synonyms:\tupset, perturb, fluster, ruffle, disconcert, unnerve, disquiet, disturb", "\"the thought of questioning Toby agitated him extremely\"", "معنی : ناراحت و پریشان کردن", "کد واژه :آجیتو!", "مثال : چرا <font color='black'>آجیتو</font>  ناراحت و <font color='red'>پریشون </font>کردی؟", R.drawable.agitate,new TestEntry("generate","push","erode","stimulate"),"stimulate"));
        wordsList.add(new DictionaryEntry(1,"talent", "/ˈtalənt/", "Natural aptitude or skill.", "synonyms:\tflair, aptitude, facility, gift, knack, technique, touch, bent, ability", "\"he possesses more talent than any other player\"", "معنی : استعداد", "کد واژه : تله!", "مثال : این که میگن یارو <font color='red'>با استعداد</font> یه <font color='black'>تله </font>است باور نکن!", R.drawable.talent,new TestEntry("ability","capacity","activity","desire"),"ability"));
        wordsList.add(new DictionaryEntry(1,"breed", "/briːd/", "(of animals) Mate and then produce offspring.", "synonyms:\treproduce, produce offspring, procreate, bear young", "\"toads are said to return to the pond of their birth to breed\"","معنی : تولید مثل کردن", "کد واژه : برید !", "مثال : <font color='black'>برید</font> بچه بیارید و <font color='red'>تولید مثل </font>کنید !", R.drawable.breed,new TestEntry("carve","reproduce","generate","pass"),"reproduce"));
        wordsList.add(new DictionaryEntry(1,"breeze", "/briːz/", "A gentle wind.", "synonyms:\tgentle wind, breath of wind, puff of air, current of air, flurry of air, gust", "\"tantalizing cooking smells wafted on the evening breeze\"","معنی : نسیم", "کد واژه : بریز !", "مثال : <font color='red'>نسیم</font> جان چایی <font color='black'>بریز</font> !", R.drawable.breeze,new TestEntry("faint","weather","light wind","gentle"),"light wind"));
        wordsList.add(new DictionaryEntry(1,"broad", "/brɔːd/", "Having a distance larger than usual from side to side; wide.", "synonyms:\twide, large, big", "\"a broad staircase\"","معنی : عریض", "کد واژه : road  !", "مثال : این<font color='black'> road </font><font color='red'>عریض</font> و پهن است !", R.drawable.broad,new TestEntry("wide","massive","perilous","fade"),"wide"));
        wordsList.add(new DictionaryEntry(1,"carve", "/kärv/", "Cut (a hard material) in order to produce an aesthetically pleasing object or design.", "synonyms:\tsculpt, sculpture", "\"the wood was carved with runes\"","معنی : حکاکی کردن", "کد واژه : car !", "مثال : بدنه ی این<font color='black'> car </font>ها رو <font color='red'>حکاکی کردن </font>!", R.drawable.carve,new TestEntry("generate","cut","dominate","cure"),"cut"));
        wordsList.add(new DictionaryEntry(1,"cast", "/kast/", "Throw (something) forcefully in a specified direction.", "synonyms:\tthrow, toss, fling, pitch, hurl, lob", "\"lemmings cast themselves off the cliff\"","معنی : کاستن", "کد واژه : کاست !", "مثال : از این ریختن و<font color='red'> انداختن </font>ها باید<font color='black'> کاست </font>!", R.drawable.cast,new TestEntry("collapse","blade","throw","fade"),"throw"));
        wordsList.add(new DictionaryEntry(1,"catch up", "/ˈkaCHˌəp/", "Succeed in reaching a person who is ahead of one.", "* Do work or other tasks that one should have done earlier.", "\"he normally used the afternoons to catch up on paperwork\"","معنی : سبقت گرفتن", "کد واژه : کچاپ !", "مثال : توی استفاده از سس <font color='black'> کچاپ</font> باید از بقیه <font color='red'>سبقت گرفت</font>!", R.drawable.catchup,new TestEntry("merge","lease","eclipse","reach"),"reach"));
        wordsList.add(new DictionaryEntry(1,"classify", "/ˈklasəˌfī/", "arrange (a group of people or things) in classes or categories according to shared qualities or characteristics.", "synonyms:\tcategorize, group, grade, rank, rate, order, organize, range", "\"mountain peaks are classified according to their shape\"","معنی : طبقه بندی کردن", "کد واژه : کلاس !", "مثال : این <font color='black'>کلاس</font>  ها رو باید<font color='red'> طبقه بندی کرد</font> !", R.drawable.classify,new TestEntry("categorize","handle","agitate","rejuvenate"),"categorize"));
        wordsList.add(new DictionaryEntry(1,"community", "/kəˈmyo͞onədē/", "A group of people living in the same place or having a particular characteristic in common.", "synonyms:\tgroup, body, set, circle, clique, faction", "\"Rhode Island's Japanese community\"","معنی : اجتماع", "کد واژه : کامیون !", "مثال : <font color='black'>کامیون </font>ها برای خودشون یه <font color='red'>اجتماع </font>تشکیل دادن !", R.drawable.community,new TestEntry("inhabitants","group","people","nation"),"group"));
        wordsList.add(new DictionaryEntry(1,"coincide", "/ˌkōənˈsīd/", "Occur at or during the same time.", "synonyms:\toccur simultaneously, happen together, be concurrent, concur", "\"publication is timed to coincide with a major exhibition\"","معنی : مطابقت داشتن", "کد واژه : coin !", "مثال : این<font color='black'> coin </font>ها با هم <font color='red'>مطابقت ندارن </font>!", R.drawable.coincide,new TestEntry("blend","classify","occur","throw"),"occur"));
        wordsList.add(new DictionaryEntry(1,"complex", "/ˌkämˈpleks/", "Consisting of many different and connected parts.", "synonyms:\tcompound, composite, multiplex", "\"a complex network of water channels\"","معنی : پیچیده", "کد واژه : ب کمپلکس !", "مثال : ب <font color='black'>کمپلکس </font>چیز <font color='red'>پیچیده ای </font>است !", R.drawable.complex,new TestEntry("renowned","involved","consisted","complicated"),"complicated"));
        wordsList.add(new DictionaryEntry(1,"rejuvenate", "/rɪˈdʒuːvəneɪt/", "Make (someone or something) look or feel better, younger, or more vital.", "synonyms:\trevive, revitalize, renew, regenerate, restore, breathe new life into, make someone feel young again", "\"a bid to rejuvenate the town centre\"","معنی : دوباره جوان کردن", "کد واژه : re (همیشه به معنی دوباره است ) + جونور(جانور) !", "مثال : بعضی از این <font color='black'>جونورا </font>آدم و<font color='red'> دوباره جوون میکنن</font> !", R.drawable.rejuvenate,new TestEntry("revive","replace","occur","gentle"),"revive"));
        wordsList.add(new DictionaryEntry(1,"relatively", "/ˈrɛlətɪvli/", "In relation, comparison, or proportion to something else.", "synonyms:\tcomparatively, in comparison, by comparison, proportionately; quite, fairly, reasonably", "\"they were very poor, but, relatively speaking, they had been lucky\"","معنی : نسبتأ", "کد واژه : re (همیشه به معنی دوباره است ) + لطیف !", "مثال : دخترِ <font color='red'>نسبتاً</font> (تا اندازه ای ) <font color='black'>لطیفِ </font>!", R.drawable.relatively,new TestEntry("completely","comparatively","remotely","gently"),"comparatively"));
        wordsList.add(new DictionaryEntry(1,"remedial", "/rɪˈmiːdɪəl/", "Giving or intended as a remedy or cure.", "* Provided or intended for children with learning difficulties.", "\"remedial surgery\"","معنی : شفابخش", "کد واژه : re (همیشه به معنی دوباره است )  + media (رسانه ) !", "مثال : بعضی <font color='black'>رسانه </font>ها <font color='red'>شفابخشن </font>!", R.drawable.remedial,new TestEntry("complex","auditory","therapeutic","intended"),"therapeutic"));
        wordsList.add(new DictionaryEntry(1,"reminiscent", "/ˌreməˈnis(ə)nt/", "Tending to remind one of something.", "synonyms:\tsimilar to, comparable with, evocative of, suggestive of, redolent of", "\"the sights were reminiscent of my childhood\"","معنی : یادبود", "کد واژه: re (همیشه به معنی دوباره است ) +mini  + سنگ!", "مثال : این <font color='black'>سنگ کوچک</font><font color='red'> یادآور </font>گذشته است !", R.drawable.reminiscent,new TestEntry("addicting","indulging","remembering","throwing"),"remembering"));
        wordsList.add(new DictionaryEntry(1,"remnant", "/ˈremnənt/", "A small remaining quantity of something.", "synonyms:\tremains, remainder, leftovers, residue, rest", "\"the remnants of the picnic\"","معنی :پس مانده", "کد واژه : re (همیشه به معنی دوباره است ) + منت !", "مثال : سر این <font color='red'>پس مانده ها</font> (باقی مانده ها) بر من<font color='black'> منت </font>نذار !", R.drawable.remnant,new TestEntry("excess","talent","complex","remains"),"remains"));
        wordsList.add(new DictionaryEntry(1,"remote", "/rəˈmōt/", "(of a place) Situated far from the main centers of population; distant.", "synonyms:\tfaraway, distant, far, far off, far removed, extrasolar", "\"a remote Oregon valley\"","معنی : دور", "کد واژه : re (همیشه به معنی دوباره است ) + موت (مرگ) !", "مثال : <font color='black'>موت </font>به ما <font color='red'>دور</font> نیست  !", R.drawable.remote,new TestEntry("far","remedial","remnant","capacity"),"far"));
        wordsList.add(new DictionaryEntry(1,"renovation", "/ˌrenəˈvāSH(ə)n/", "The action of renovating a building.", "synonyms:\tmodernization, restoration, redecoration, refurbishment, revamping", "\"this property is in need of complete renovation\"","معنی : نوسازی", "کد واژه : re (همیشه به معنی دوباره است ) + نو (جدید) و + شن !", "مثال : این <font color='black'>شن </font>های <font color='black'>نو </font>برای<font color='red'> نوسازی </font> خوبه !", R.drawable.renovation,new TestEntry("reputation","modernization","domination","burgeoning"),"modernization"));
        wordsList.add(new DictionaryEntry(1,"renowned", "/rəˈnound/", "Known or talked about by many people; famous.", "synonyms:\tfamous, celebrated, famed, eminent, distinguished, acclaimed, illustrious", "\"a restaurant renowned for its Southwestern-style food\"","معنی : مشهور", "کد واژه : re (همیشه به معنی دوباره است ) + noun (اسم) !", "مثال : این <font color='black'>اسم </font>خیلی <font color='red'>مشهوره </font>!", R.drawable.renowned,new TestEntry("talent","perilous","famous","community"),"famous"));
        wordsList.add(new DictionaryEntry(1,"reputation", "/ˌrepyəˈtāSH(ə)n/", "The beliefs or opinions that are generally held about someone or something.", "synonyms:\tname, good name, character, repute, standing, stature, status, position", "\"his reputation was tarnished by allegations that he had taken bribes\"","معنی : شهرت", "کد واژه : re (همیشه به معنی دوباره است ) + put + tion (همیشه کلمه رو اسم میکنه و به تنهایی معنی نداره) ", "مثال: هر چی <font color='black'>اینجا </font>بذاری<font color='red'> شهرت </font>پیدا میکنی!", R.drawable.reputation,new TestEntry("renovation","reminiscent","capacity","status"),"status"));
        wordsList.add(new DictionaryEntry(1,"requisite", "/ˈrekwəzət/", "Made necessary by particular circumstances or regulations.", "synonyms:\tnecessary, required, prerequisite, essential, indispensable, vital", "\"the application will not be processed until the requisite fee is paid\"","معنی : لازم", "کد واژه : re (همیشه به معنی دوباره است ) + quiz + it !", "مثال : این <font color='black'>امتحان </font><font color='red'> لازمه </font>!", R.drawable.requisite,new TestEntry("necessary","remedial","complex","tricky"),"necessary"));
        wordsList.add(new DictionaryEntry(1,"dominate", "/ˈdɒmɪneɪt/", "Have power and influence over.", "synonyms:\tcontrol, influence, exercise control over, be in control of, command", "\"the company dominates the market for operating system software\"","معنی : تسلط پیدا کردن", "کد واژه : دومینو !", "مثال : خیلی سعی میکنم به بازی <font color='black'>دومینو </font><font color='red'>تسلط پیدا کنم </font>! ", R.drawable.dominate,new TestEntry("eclipse","control","lease","breed"),"control"));
        wordsList.add(new DictionaryEntry(1,"subsidy", "/ˈsʌbsɪdi", "A sum of money granted by the state or a public body to help an industry or business keep the price of a commodity or service low.", "synonyms:\tgrant, allowance, endowment, contribution, donation, bursary, gift", "\"a farm subsidy\"","معنی : یارانه", "کد واژه : سابیدی !", "مثال : انقد همه چی و<font color='black'> سابیدی</font> بهت <font color='red'>یارانه </font>تعلق میگیره !", R.drawable.subsidy,new TestEntry("bond","coincide","grant","catch up"),"grant"));
        wordsList.add(new DictionaryEntry(1,"ascertain", "/ˌasəˈteɪn/", "Find (something) out for certain; make sure of.", "synonyms:\tfind out, discover, get/come to know, work out, make out, fathom (out), become aware of, learn, ferret out, dig out/up, establish, fix, determine, settle, decide, verify", "\"an attempt to ascertain the cause of the accident\"","معنی : ثابت کردن", "کد واژه : اسیر شَن !", "مثال : با این کار <font color='red'>ثابت کردن </font>که میخان<font color='black'> اسیر شن</font> !", R.drawable.ascertain,new TestEntry("cast","carve","renovate","discover"),"discover"));
        wordsList.add(new DictionaryEntry(1,"auditory", "/ˈɔːdɪt(ə)ri/", "Relating to the sense of hearing.", "\"the auditory nerves\"", "","معنی : شنوایی", "کد واژه : عادی طوری !", "مثال : با یه حالت <font color='black'>عادی طوری </font>گفت که<font color='red'> شنواییش</font> مشکل داره !", R.drawable.auditory,new TestEntry("sense of hearing","audience","related to sight","observance"),"sense of hearing"));
        wordsList.add(new DictionaryEntry(1,"bond", "/bɒnd/", "A thing used to tie something or to fasten things together.", "synonyms:\tchains, fetters, shackles, manacles, irons", "\"she brushed back a curl which had strayed from its bonds\"","معنی : غل و زنجیر کردن", "کد واژه : باند (فرودگاه) !", "مثال : تو باند فرودگاه غل و زنجیرش کردن !", R.drawable.bond,new TestEntry("absence","chain","auditory","community"),"chain"));
        wordsList.add(new DictionaryEntry(1,"burgeoning", "/ˈbəːdʒ(ə)n/", "Begin to grow or increase rapidly; flourish.", "synonyms:\tgrow rapidly, increase rapidly/exponentially, expand, spring up, shoot up, swell, explode, boom, mushroom, proliferate, snowball, multiply, become more numerous", "\"manufacturers are keen to cash in on the burgeoning demand\"","معنی : جوانه زدن", "کد واژه : burger (برگر) !", "مثال : از بس <font color='black'>برگر </font>خوردم داره ازم <font color='red'>جوانه میزنه</font>!", R.drawable.burgeoning,new TestEntry("ascertain","classify","flourish","triumph"),"flourish"));
        wordsList.add(new DictionaryEntry(1,"capacity", "/kəˈpasɪti/", "The maximum amount that something can contain.", "synonyms:\tvolume, cubic measure; size, dimensions, measurements, magnitude", "\"the capacity of the freezer is 1.1 cubic feet\"","معنی : گنجایش", "کد واژه : cap + city !", "مثال : <font color='black'>کلاهتو (cap) </font>تو <font color='black'>شهر(city) </font>بردار اینجا <font color='red'>گنجایشش</font> و ندارن!", R.drawable.capacity,new TestEntry("complex","reputation","requisition","potential"),"potential"));
        wordsList.add(new DictionaryEntry(2,"adopt", "/əˈdɒpt/", "1. Legally take (another's child) and bring it up as one's own.\n2. choose to take up or follow (an idea, method, or course of action).", "synonyms:\tembrace, take on, acquire, affect, espouse, assume, appropriate, arrogate", "\"there are many people eager to adopt a baby\"\n\"this approach has been adopted by many big banks\"", "معنی : قبول کردن", "کد واژه : آداپتور", "مثال : میدونستید <font color='black'> آداپتور </font> جریان برق با هر ولتاژی و <font color='red'> قبول میکنه </font>؟", R.drawable.adopt,new TestEntry("embrace","absorb","access","snap"),"embrace" ));
        wordsList.add(new DictionaryEntry(2,"abound", "/əˈbound/", "Exist in large numbers or amounts.", "synonyms:\tbe plentiful, be abundant, be numerous, proliferate, super abound", "\"rumors of a further scandal abound\"", "معنی : پر بودن از", "کد واژه : بند !", "مثال : <font color='black'>بند </font>بند این کشور <font color='red'>پر شده از</font> آبادانی!", R.drawable.abound,new TestEntry("painful","plentiful","discreet","stable"),"plentiful" ));
        wordsList.add(new DictionaryEntry(2,"absence", "/ˈabsəns/", "1. The state of being away from a place or person.\n2. The nonexistence or lack of.", "synonyms:\tnonattendance, nonappearance, absenteeism, lack, want, nonexistence, unavailability", "\"the letter had arrived during his absence\"\n\"she found his total absence of facial expression disconcerting\"", "معنی : فقدان", "کد واژه : آبسه!", "مثال : <font color='black'>آبسه </font>از نتایج <font color='red'>فقدان </font>بهداشت است!", R.drawable.absence,new TestEntry("non-involvement","dedicated","non-appearance","coordinated"),"non-appearance" ));
        wordsList.add(new DictionaryEntry(2,"absorb", "/əbˈzôrb,əbˈsôrb/", "1. Take in or soak up (energy, or a liquid or other substance) by chemical or physical action, typically gradually.\n2. Engross the attention of (someone).", "synonyms:\tsoak up, suck up, draw up/in, take up/in, blot up, mop up, captivate by, occupy with, preoccupy with, engage in", "\"buildings can be designed to absorb and retain heat\"\n\"the work absorbed him and continued to make him happy\"", "معنی : جذب شدن", "کد واژه : آب + سرب !", "مثال : <font color='black'>سرب </font>موجود در آب میتواند <font color='red'>جذب </font>بدن شود.", R.drawable.absorb,new TestEntry("bring in","involve in","shift","take in"),"take in" ));
        wordsList.add(new DictionaryEntry(2,"accelerate", "/əkˈseləˌrāt/", "1. (of a vehicle or other physical object) Begin to move more quickly.\n2. Increase in amount or extent.", "synonyms:\tspeed up, go faster, gain momentum, increase speed, pick up speed, gather speed", "\"the car accelerated toward her\"\n\"inflation started to accelerate\"", "معنی : با سرعت انجام دادن", "کد واژه : اکثر لرها!", "مثال : <font color='black'>اکثر لر </font>ها کاراشون و <font color='red'>با سرعت انجام میدن</font>.", R.drawable.accelerate,new TestEntry("confront","speed up","increase","dedicate"),"speed up" ));
        wordsList.add(new DictionaryEntry(2,"accessible", "/əkˈsesəb(ə)l/", "1. (of a place) Able to be reached or entered.\n2. (of a person, typically one in a position of authority or importance) Friendly and easy to talk to; approachable.", "synonyms:\treachable, attainable, approachable, approachable, friendly, agreeable, obliging, congenial, affable, cordial, welcoming, easygoing, pleasant", "\"the town is accessible by bus\"\n\"he is more accessible than most tycoons\"", "معنی : در دسترس", "کد واژه : عکس سیبیل!", "مثال : <font color='black'>عکس سیبیل </font>همه باید <font color='red'> در دسترس </font>باشه.", R.drawable.access,new TestEntry("comfortable","controllable","reachable","adoptable"),"reachable" ));
        wordsList.add(new DictionaryEntry(2,"accommodation", "/əˌkäməˈdāSH(ə)n/", "!. A room, group of rooms, or building in which someone may live or stay\n2. A convenient arrangement; a settlement or compromise.", "synonyms:\thousing, lodging(s), living quarters, quarters, rooms, arrangement, understanding, settlement, accord", "\"the cost includes airfare and hotel accommodations\"\n\"accommodation to a separate political entity was not possible\"", "معنی : منزل", "کد واژه : کمدشون!", "مثال : <font color='black'>کمدشون </font>و تو <font color='red'> منزل </font>ما گذاشتند.", R.drawable.accommodate,new TestEntry("accessing","covering","joining","housing"),"housing" ));
        wordsList.add(new DictionaryEntry(2,"accompany", "/əˈkəmp(ə)nē/", "Go somewhere with (someone) as a companion or escort.", "synonyms:\tgo with, travel with, keep someone company, tag along with, hang out with", "\"the two sisters were to accompany us to New York\"", "معنی : همراهی کردن", "کد واژه : کمپانی!", "مثال : <font color='black'>این کمپانی </font>همیشه ما رو <font color='red'>همراهی کرده</font>!", R.drawable.accompany,new TestEntry("go with","take in","catch up","accelerate"),"go with" ));
        wordsList.add(new DictionaryEntry(2,"attribute", "/əˈtriˌbyo͞ot/", "1. Regard something as being caused by (someone or something).\n2. A quality or feature regarded as a characteristic or inherent part of someone or something.", "synonyms:\tascribe to, assign to, accredit to, credit to, impute to, quality, characteristic, trait, feature, element, aspect, property, sign, hallmark, mark, distinction", "\"he attributed the firm's success to the efforts of the managing director\"\n\"flexibility and mobility are the key attributes of our army\"", "معنی : خصوصیت", "کد واژه : عطر بوتیک!", "مثال : از <font color='red'>خصوصیات </font><font color='black'>عطر بوتیک </font>ماندگاریش!", R.drawable.attribute,new TestEntry("contribute","characteristic","discreet","involve"),"characteristic" ));
        wordsList.add(new DictionaryEntry(2,"blade", "/blād/", "The flat cutting edge of a knife, saw, or other tool or weapon.", "Short for razor blade.", "\"Lydia is being taught to run on blades\"", "معنی : تیغه", "کد واژه : بلد !", "مثال : <font color='black'>بلدی </font>با این <font color='red'>تیغه </font>کار کنی ؟ ", R.drawable.blade,new TestEntry("sharp","covered","knife","flat"),"knife" ));
        wordsList.add(new DictionaryEntry(2,"discreet", "/diˈskrēt/", "Careful and circumspect in one's speech or actions, especially in order to avoid causing offense or to gain an advantage.", "synonyms:\tcareful, circumspect, cautious, wary, chary, guarded", "\"we made some discreet inquiries\"", "معنی : احتیاط کردن", "کد واژه : دستگیرت!", "مثال : اگه اینجا <font color='red'>احتیاط </font>نکنی <font color='black'>دستگیرت </font> میکنن.", R.drawable.discreet,new TestEntry("show case","phenomena","capacity","careful"),"careful" ));
        wordsList.add(new DictionaryEntry(2,"involve", "/inˈvälv/", "(of a situation or event) Include (something) as a necessary part or result.", "synonyms:\trequire, necessitate, demand, call for", "\"his transfer to another school would involve a lengthy assessment procedure\"", "معنی : درگیر شدن", "کد واژه : این ولوو!", "مثال : این اتوبوس های <font color='black'>ولوو </font> هم که خراب بشن آدم و گرفتار و<font color='red'> درگیر میکنن</font>.", R.drawable.involve,new TestEntry("include","access","handle","coincide"),"include" ));
        wordsList.add(new DictionaryEntry(2,"stabilize", "/ˈstābəˌlīz/", "Make or become unlikely to give way or overturn.", "\"the craft was stabilized by throwing out the remaining ballast\"", "\"an emergency program designed to stabilize the economy\"", "معنی : محکم و استوار", "کد واژه : اسطبل!", "مثال : باید یه کاری کنیم این <font color='black'>اسطبل </font>ها محکم و<font color='red'>  استوار</font> بمونن!", R.drawable.stable,new TestEntry("keep","maintain a given level","support","fluctuate"),"maintain a given level" ));
        wordsList.add(new DictionaryEntry(2,"robust", "/rōˈbəst/", "Strong and healthy; vigorous.", "synonyms:\tstrong, vigorous, sturdy, tough, powerful, solid, muscular, sinewy", "\"the Caplans are a robust, healthy lot\"", "معنی : قوی هیکل و تنومند", "کد واژه : روباه!", "مثال : میگی طرف خیلی <font color='black'>روباست</font> گرچه قوی هیکل و<font color='red'> تنومنده</font>!", R.drawable.robust,new TestEntry("violent","resistant","strong","careful"),"strong" ));
        wordsList.add(new DictionaryEntry(2,"rural", "/ˈro͝orəl/", "In, relating to, or characteristic of the countryside rather than the town.", "synonyms:\tcountry, countryside, bucolic, rustic, pastoral", "\"remote rural areas\"", "معنی : روستایی", "کد واژه : رو ریل!", "مثال : تو این منطقه <font color='red'>روستایی </font>همه چی رو<font color='black'> ریله </font>!", R.drawable.rural,new TestEntry("farm","household","urban","rustic"),"rustic"));
        wordsList.add(new DictionaryEntry(2,"phenomena", "/fəˈnɒmɪnə/", "A fact or situation that is observed to exist or happen, especially one whose cause or explanation is in question.", "synonyms:\toccurrence, event, happening, fact, situation, circumstance, experience, case, incident, episode, sight, appearance, thing", "\"glaciers are interesting natural phenomena\"", "معنی : پدیده ، اثر", "کد واژه : فنا منا !", "مثال : <font color='black'>فنا </font> (نابودی) <font color='black'>منا</font> تو زندگی من <font color='red'>اثری </font>نداشته!", R.drawable.phonemena,new TestEntry("remarkable","universal","traditional","circumstance"),"remarkable"));
        wordsList.add(new DictionaryEntry(2,"pitch", "/pɪtʃ/", "Set (one's voice or a piece of music) at a particular pitch.", "Set or aim at a particular level, target, or audience.", "\"you've pitched the melody very high\"", "معنی : استقرار", "کد واژه : پیچ!", "مثال : برای <font color='red'>استقرار </font>این چادر به <font color='black'>پیچ </font> احتیاج هست!", R.drawable.pitch,new TestEntry("tune in","set up","reach","stabilize"),"set up"));
        wordsList.add(new DictionaryEntry(2,"pleasure", "/ˈplɛʒə/", "A feeling of happy satisfaction and enjoyment.", "synonyms:\thappiness, delight, joy, gladness, rapture, glee, satisfaction, gratification, fulfilment", "\"she smiled with pleasure at being praised\"", "معنی : لذت بخش", "کد واژه : پله + ژرف!", "مثال : این <font color='black'>پله های ژرف</font> چه <font color='red'>لذت بخشه </font>!", R.drawable.pleasure,new TestEntry("annoyance","passion","enjoyment","stable"),"enjoyment" ));
        wordsList.add(new DictionaryEntry(2,"pollution", "/pəˈluːʃ(ə)n/", "The presence in or introduction into the environment of a substance which has harmful or poisonous effects.", "synonyms:\tcontamination, contaminating, adulteration, adulterating, tainting, impurity, fouling, befouling, foulness, dirtiness, dirtying, soiling, filthiness, infection", "\"the level of pollution in the air is rising\"", "معنی : آلودگی", "کد واژه : پلو شرت!", "مثال : این <font color='black'>پلو شرت</font> و بپوشی از <font color='red'>آلودگی </font>در امانی!", R.drawable.pollution,new TestEntry("impurity","pleasure","controversy","shortage"),"impurity"));
        wordsList.add(new DictionaryEntry(2,"shift", "/ʃɪft/", "Move or cause to move from one place to another, especially over a small distance.", "synonyms:\tmove, carry, transfer, transport, convey, take, bring, bear, lug, cart, haul, fetch", "\"a team from the power company came to shift the cables away from the house\"", "معنی : انتقال دادن", "کد واژه : شیفت!", "مثال : باید <font color='black'>شیف</font> (کاری) من و به یه زمان دیگه ای <font color='red'>انتقال بدین</font>!", R.drawable.shift,new TestEntry("stabilize","transfer","blade","coordinate"),"transfer"));
        wordsList.add(new DictionaryEntry(2,"concerned", "/kənˈsərnd/", "Worried, troubled, or anxious.", "synonyms:\tworried, anxious, upset, perturbed, troubled, distressed, uneasy, apprehensive", "\"the villagers are concerned about burglaries\"","معنی : مورد علاقه", "کد واژه : کنسرت !", "مثال : <font color='black'>کنسرت </font>موضوع <font color='red'>مورد علاقه </font>ی منه !", R.drawable.conerned,new TestEntry("accessible","robust","worried","discreet"),"worried"));
        wordsList.add(new DictionaryEntry(2,"concur", "/kənˈkər/", "Be of the same opinion; agree.", "synonyms:\tagree, be in agreement, go along, fall in, be in sympathy", "\"the authors concurred with the majority\"","معنی : موافقت", "کد واژه : کنکور !", "مثال : من اصلاً با <font color='black'>کنکور</font> <font color='red'>موافق </font>نیستم !", R.drawable.concur,new TestEntry("coincide","adopt","involve","happen"),"happen"));
        wordsList.add(new DictionaryEntry(2,"confront", "/kənˈfrənt/", "Meet (someone) face to face with hostile or argumentative intent.", "synonyms:\tchallenge, face (up to), come face to face with, meet, accost", "\"300 policemen confronted an equal number of union supporters\"","معنی : روبرو شدن", "کد واژه : front !", "مثال : از سمت<font color='black'> front </font>با ما <font color='red'>رویرو</font> شدن !", R.drawable.confront,new TestEntry("challenge","concur","dire","accommodate"),"challenge"));
        wordsList.add(new DictionaryEntry(2,"controversy", "/ˈkäntrəˌvərsē/", "Disagreement, typically when prolonged, public, and heated.", "synonyms:\tdisagreement, dispute, argument, debate, dissension, contention", "\"he sometimes caused controversy because of his forceful views\"","معنی : بحث انگیز", "کد واژه : کنتور وسیع !", "ثال : موضوع این <font color='black'>کنتور وسیع </font>ها چه جنجالی و<font color='red'> بحث انگیز </font>شده !", R.drawable.conversery,new TestEntry("showcase","disagreement","solitary","structure"),"disagreement"));
        wordsList.add(new DictionaryEntry(2,"coordinate", "/kōˈôrdəˌnāt/", "Bring the different elements of (a complex activity or organization) into a relationship that will ensure efficiency or harmony.", "synonyms:\torganize, arrange, order, systematize, harmonize, correlate, synchronize", "\"he had responsibility for coordinating Chicago's transportation services\"","معنی : هماهنگ کردن", "کد واژه : کردی !", "مثال : چه قشنگ رقص <font color='black'>کردی</font> و با هم <font color='red'>هماهنگ کردن </font>!", R.drawable.coordinate,new TestEntry("involve","snap","correlate","confront"),"correlate"));
        wordsList.add(new DictionaryEntry(2,"crucial", "/ˈkro͞oSHəl/", "Decisive or critical, especially in the success or failure of something.", "synonyms:\tpivotal, critical, key, climacteric, decisive, deciding; life-and-death", "\"negotiations were at a crucial stage\"","معنی : مهم", "کد واژه : کروکی !", "مثال : داشتن <font color='black'>کروکی </font> این منطقه خیلی<font color='red'> مهمه </font>!", R.drawable.crucial,new TestEntry("phenomena","deed","controversy","necessary"),"necessary"));
        wordsList.add(new DictionaryEntry(2,"cuisine", "/kwəˈzēn/", "A style or method of cooking, especially as characteristic of a particular country, region, or establishment.", "synonyms:\tcooking, cookery, food, dishes", "\"much Venetian cuisine is based on seafood\"","معنی : دست پخت", "کد واژه : کو این زن ؟!", "مثال : <font color='black'>کو این زن</font> با این<font color='red'> دستپختش </font>!", R.drawable.cuisine,new TestEntry("cooking","pollution","dedication","scholar"),"cooking"));
        wordsList.add(new DictionaryEntry(2,"dedicate", "/ˈdedəˌkāt/", "Devote (time, effort, or oneself) to a particular task or purpose.", "synonyms:\tdevote, commit, pledge, give, surrender, sacrifice", "\"Joan has dedicated her life to animals\"","معنی : اختصاص دادن", "کد واژه : دَدی + کت (cat) !", "مثال : <font color='black'>دَدی </font> تمام وقتش و به این<font color='black'> کَت </font><font color='red'>اختصاص داده </font>!", R.drawable.dedicate,new TestEntry("sparse","devote","accompany","absorb"),"devote"));
        wordsList.add(new DictionaryEntry(2,"deed", "/dēd/", "An action that is performed intentionally or consciously.", "synonyms:\tact, action; feat, exploit, achievement, accomplishment", "\"doing good deeds\"","معنی : کردار", "کد واژه : دید !", "مثال : عمل و<font color='red'> کردار </font>من و<font color='black'> دید </font>!", R.drawable.deed,new TestEntry("dire","pitch","act","accelerate"),"act"));
        wordsList.add(new DictionaryEntry(2,"dire", "/ˈdī(ə)r/", "(of a situation or event) Extremely serious or urgent.", "synonyms:\tterrible, dreadful, appalling, frightful, awful, atrocious, grim, alarming", "\"dire consequences\"","معنی : وحشتناک", "کد واژه : دیرِ !", "مثال : دیگه <font color='black'>دیره </font>و بیرون<font color='red'> وحشتناک </font>شده !", R.drawable.dire,new TestEntry("accessible","attribute","rural","dreadful"),"dreadful"));
        wordsList.add(new DictionaryEntry(2,"shortage", "/ˈSHôrdij/", "A state or situation in which something needed cannot be obtained in sufficient amounts.", "synonyms:\tscarcity, sparseness, sparsity, dearth, paucity, poverty, insufficiency, deficiency", "\"a shortage of hard cash\"","معنی : کمبود", "کد واژه : short + age !", "مثال : دچار<font color='red'> کمبود </font><font color='black'>کم سن </font>و سال شدیم !", R.drawable.shortage,new TestEntry("deficiency","slippery","deed","showcase"),"deficiency"));
        wordsList.add(new DictionaryEntry(2,"showcase", "/ˈSHōˌkās/", "A glass case used for displaying articles in a store or museum.", "* Exhibit; display.", "\"the gallery will provide a showcase for Atlanta's young photographers\"\n\"the albums showcase his production skills\"","معنی : ویترین", "کد واژه : show + case !", "مثال : این <font color='red'>ویترین </font><font color='black'>جای نمایش </font>شده !", R.drawable.showcase,new TestEntry("polluted","display","confronted","crucial"),"display"));
        wordsList.add(new DictionaryEntry(2,"slippery", "/ˈslip(ə)rē/", "(of a surface or object) Difficult to hold firmly or stand on because it is smooth, wet, or slimy.", "synonyms:\ticy, greasy, oily, glassy, smooth, slimy, wet", "\"slippery ice\"","معنی : لیز خوردن", "کد واژه : Sleep !", "مثال : جدیداً هی <font color='black'>خواب </font>میبینم که پام <font color='red'>لیز </font>میخوره !", R.drawable.slippery,new TestEntry("absence","access","greasy","robust"),"greasy"));
        wordsList.add(new DictionaryEntry(2,"slope", "/slōp/", "A surface of which one end or side is at a higher level than another; a rising or falling surface.", "synonyms:\tgradient, incline, angle, slant, inclination, pitch, decline, ascent, declivity, rise", "\"he slithered helplessly down the slope\"","معنی : سرازیری", "کد واژه : s + لّپ !", "مثال : تو <font color='red'>سرازیری </font>بودیم که <font color='black'>لّپمو</font> کشید !", R.drawable.slope,new TestEntry("status","showcase","abound","gradient"),"gradient"));
        wordsList.add(new DictionaryEntry(2,"snap", "/snap/", "Break or cause to break suddenly and completely, typically with a sharp cracking sound.", "synonyms:\tbreak, fracture, splinter, come apart, split, crack", "\"guitar strings kept snapping\"","معنی : گاز گرفتن", "کد واژه : s + nap (چرت زدن) !", "مثال : موقع <font color='black'>چرت زدن</font> زبونش و<font color='red'> گاز گرفت</font>!", R.drawable.snap,new TestEntry("break","pitch","involve","discreet"),"break"));
        wordsList.add(new DictionaryEntry(2,"solitary", "/ˈsäləˌterē/", "Done or existing alone.", "synonyms:\tlonely, companionless, unaccompanied, by oneself, on one's own", "\"I live a pretty solitary life\"","معنی : تنهایی", "کد واژه : so + لاتاری !", "مثال : وقتی <font color='black'>لاتاری </font>قبول شد از <font color='red'>تنهایی </font>دراومد !", R.drawable.solitary,new TestEntry("rural","lonely","concerned","status"),"lonely"));
        wordsList.add(new DictionaryEntry(2,"sparse", "/spärs/", "Thinly dispersed or scattered.", "synonyms:\tscant, scanty, scattered, scarce, infrequent, few and far between", "\"areas of sparse population\"","معنی : پراکنده", "کد واژه : s + پارس !", "مثال : مردم در سرزمین<font color='black'> پارس </font>ها به طور <font color='red'>پراکنده </font>زندگی میکردند !", R.drawable.sparse,new TestEntry("shift","stabilize","scatter","blade"),"scatter"));
        wordsList.add(new DictionaryEntry(2,"status", "/ˈstādəs/", "The relative social, professional, or other standing of someone or something.", "synonyms:\tstanding, rank, ranking, position, social position, level, place, estimation", "\"an improvement in the status of women\"","معنی : مقام و منزلت اجتماعی", "کد واژه : s + تاتو !", "مثال : چرا میگن کسایی که<font color='black'> تاتو </font>دارن مقام و <font color='red'>منزلت احتماعی </font>بالایی ندارن ؟!!!", R.drawable.status,new TestEntry("stable","pitch","slope","position"),"position"));
        wordsList.add(new DictionaryEntry(2,"structure", "/ˈstrʌktʃə/", "The arrangement of and relations between the parts or elements of something complex.", "synonyms:\tconstruction, form, formation, shape, composition, fabric, anatomy, make-up", "\"the two sentences have equivalent structures\"","معنی : ساختار","کد واژه : s + تراکتور !","مثال : این <font color='black'>تراکتور</font> ها هم <font color='red'>ساختار </font>عجیبی دارن !", R.drawable.structure,new TestEntry("construction","shortage","phenomena","attribute"),"construction"));
        wordsList.add(new DictionaryEntry(3,"abroad", "/əˈbrɔːd/", "1.(adverb) In or to a foreign country or countries.\n2.(noun) Foreign countries considered collectively.", "synonyms:\toverseas, out of the country, to/in foreign parts, to/in a foreign country/land", "\"we usually go abroad for a week in May\"\n\"servicemen returning from abroad\"", "معنی : خارج از کشور", "کد واژه : آب رود", "مثال : <font color='black'> آب رود </font>های ایران به <font color='red'>خارج </font>میره!", R.drawable.abroad,new TestEntry("outside","travel","beyond","vital"),"outside"));
        wordsList.add(new DictionaryEntry(3,"disruptive", "/dɪsˈrʌptɪv/", "Causing or tending to cause disruption.", "synonyms:\ttrouble making, troublesome, unruly, rowdy, disorderly, undisciplined", "\"disruptive pupils\"", "معنی : مختل کننده", "کد واژه : دسر + اکتیو!", "مثال : <font color='black'> دسر </font>آدم و <font color='black'> اکتیو </font> میکنه ولی فعالیت های بدن و <font color='red'> مختل </font> میکنه!", R.drawable.disruptive,new TestEntry("cancellation","troublesome","collapsing","explosive"),"troublesome" ));
        wordsList.add(new DictionaryEntry(3,"appeal", "/əˈpiːl/", "1.(verb) Make a serious, urgent, or heartfelt request.\n2.(noun) A serious, urgent, or heartfelt request.", "synonyms:\task urgently/earnestly, request urgently/earnestly, make an urgent/earnest request, call, make a plea, plead, beg; sue", "\"police are appealing for information about the incident\"\n\"his mother made an appeal for the return of the ring\"", "معنی :جذابیت داشتن", "کد واژه : اپل", "مثال : شرکت <font color='black'>اپل </font>یکی از <font color='red'> جذاب </font> ترین شرکت ها در زمینه کامپیوتر هست.", R.drawable.appeal,new TestEntry("enrich","alter","ask","institute"),"ask" ));
        wordsList.add(new DictionaryEntry(3,"encourage", "/ɪnˈkʌrɪdʒ,ɛnˈkʌrɪdʒ/", "Give support, confidence, or hope to (someone).", "synonyms:\thearten, cheer, buoy up, uplift, inspire, motivate, egg on, spur on, stir, stir up, whip up", "\"we were encouraged by the success of this venture\"", "معنی : تشویق کردن", "کد واژه : گاراژ", "مثال : حتی <font color='black'>گاراژ </font>خونه یه دکتر آدم و <font color='red'>تشویق </font>به درس خوندن میکنه.", R.drawable.encourage,new TestEntry("peer","exhibit","observe","support"),"support" ));
        wordsList.add(new DictionaryEntry(3,"alter", "/ˈɔːltə,ˈɒltə/", "Change in character or composition, typically in a comparatively small but significant way.", "synonyms:\tchange, make changes to, make different, make alterations to, adjust, make adjustments to, adapt", "\"Eliot was persuaded to alter the passage\"", "معنی : اصلاح کردن", "کد واژه : هالتر", "مثال :شوهرت باید با <font color='black'>هالتر </font>بزنیش تا بتونی<font color='red'> اصلاحش </font>کنی.", R.drawable.alter,new TestEntry("change","affect","remove","become"),"change" ));
        wordsList.add(new DictionaryEntry(3,"energetic", "/ˌɛnəˈdʒɛtɪk/", "Showing or involving great activity or vitality.", "synonyms:\tactive, lively, dynamic, zestful, spirited, animated, vital, vibrant, sparkling, bouncy, bubbly, perky, bright and breezy, frisky", "\"moderately energetic exercise\"", "معنی : پر انرژی", "کد واژه : انرژی + تیک!", "مثال : کسی که همش <font color='black'>تیک انرژی </font>داره (منظور همش در حال تکاپوست) بهش میگن <font color='red'> انرژتیک</font>.", R.drawable.energetic,new TestEntry("forgetting","active","tired","expert"),"active" ));
        wordsList.add(new DictionaryEntry(3,"enrich", "/ɪnˈrɪtʃ,ɛnˈrɪtʃ/", "1. Improve or enhance the quality or value of.\n2. Make (someone) wealthy or wealthier.", "synonyms:\tenhance, make richer, improve, add to, augment, supplement, complement, boost", "\"her exposure to museums enriched her life in France\"\n\"top party members had enriched themselves\"", "معنی : غنی کردن", "کد واژه : انریکه!", "مثال : <font color='black'>انریکه </font>با استعدادش زندگیش و <font color='red'>غنی کرده </font>و کلی پول درآورده!", R.drawable.enrich,new TestEntry("increase","fertilize","improve","rise"),"improve" ));
        wordsList.add(new DictionaryEntry(3,"observer", "/əbˈzərvər/", "A person who watches or notices something.", "synonyms:\tspectator, onlooker, watcher, looker-on, fly on the wall, viewer, witness, eyewitness", "\"to a casual observer, he was at peace\"\n\"some observers expect interest rates to rise\"", "معنی : بیننده", "کد واژه : سرور!\n", "مثال : <font color='black'> سرورم </font> ما <font color='red'>بینندگان </font> از مشاهده رخ شما سیر نمیشویم!", R.drawable.observer,new TestEntry("participant","expert","fellow member","spectator"),"spectator" ));
        wordsList.add(new DictionaryEntry(3,"vital", "/ˈvīdl/", "1.(adverb) Absolutely necessary or important; essential.\n2.(noun) The body's important internal organs, especially the gut or the genitalia.", "synonyms:\tessential, of the essence, critical, crucial, key, indispensable, integral, all-important, imperative, mandatory", "\"secrecy is of vital importance\"\n\"the vital organs\"", "معنی : حیاتی", "کد واژه: ویتامین!", "مثال : مصرف انواع <font color='black'> ویتامین</font> برای بدن <font color='red'>حیاتی </font>است!", R.drawable.vital,new TestEntry("essential","tremendous","energetic","dynamic"),"essential" ));
        wordsList.add(new DictionaryEntry(3,"ancient", "/ˈān(t)SHənt/", "Belonging to the very distant past and no longer in existence.", "synonyms:\tof long ago, early, prehistoric, primeval, primordial, primitive", "\"the ancient civilizations of the Mediterranean\"", "معنی : قدیمی و باستانی", "کد واژه : آنشرلی!", "مثال : کارتون <font color='black'>آنشرلی </font>از کارتونای <font color='red'>قدیمی و باستانی </font>است!", R.drawable.ancient,new TestEntry("worldly","vital","old","academic"),"old" ));
        wordsList.add(new DictionaryEntry(3,"proponent", "/prəˈpəʊnənt/", "A person who advocates a theory, proposal, or course of action.", "synonyms:\tadvocate, supporter, upholder, exponent, promoter, adherent, endorser", "\"a strong proponent of the free market and liberal trade policies\"","معنی : طرفدار", "کد واژه : پر پونه !", "مثال : همیشه<font color='red'> طرفدار </font>آش <font color='black'>پُر پونه </font> بودم!", R.drawable.proponent,new TestEntry("observer","accompany","opponent","supporter"),"supporter" ));
        wordsList.add(new DictionaryEntry(3,"reluctant", "/rɪˈlʌkt(ə)nt/", "Unwilling and hesitant; disinclined.", "synonyms:\tunwilling, disinclined, unenthusiastic, grudging, resistant, resisting", "\"today, many ordinary people are still reluctant to talk about politics\"","معنی : مخالف", "کد واژه : ریلکسند!", "مثال : کسایی که <font color='red'>مخالفت </font>میکنند چه <font color='black'>ریلکسند</font>!", R.drawable.reluctant,new TestEntry("unwilling","eager","proponent","patient"),"unwilling"));
        wordsList.add(new DictionaryEntry(3,"patent", "/ˈpat(ə)nt/", "A government authority or licence conferring a right or title for a set period, especially the sole right to exclude others from making, using, or selling an invention.", "synonyms:\tcopyright, licence, legal protection, right, performing right, permit", "\"he took out a patent for an improved steam hammer\"","معنی : جواز حق انحصار", "کد واژه : پَته!", "مثال : برای گرفتن یه<font color='red'> جواز حق انحصاری </font><font color='black'>پته </font>همه رو ریخت رو آب!", R.drawable.patent,new TestEntry("letter","licence","invention","status"),"licence"));
        wordsList.add(new DictionaryEntry(3,"peer", "/pɪə/", "Look with difficulty or concentration at someone or something.", "synonyms:\tsquint, look closely/earnestly, try to see, look through narrowed eyes, narrow one's eyes", "\"Faye peered at her with suspicion\"","معنی : بیشتر نگریستن", "کد واژه : پیر !", "مثال : هر چی<font color='black'> پیر </font>میشی بیشتر به همه چی <font color='red'>خیره میشی </font>!", R.drawable.peer,new TestEntry("join","observe","glance","dedicate"),"glance"));
        wordsList.add(new DictionaryEntry(3,"exhibit", "/ɪɡˈzɪbɪt/", "publicly display (a work of art or item of interest) in an art gallery or museum or at a trade fair.", "synonyms:\tput on display, put on show, display, show, show to the public, put on public view", "\"only one sculpture was exhibited in the artist's lifetime\"","معنی : نمایش دادن", "کد واژه : اکسی (قرص) بود!", "مثال : فک کنم طرف <font color='black'>اکسی بود</font> از خودش <font color='red'>نمایش در می آورد</font>!", R.drawable.exhibit,new TestEntry("paint","refer","collect","display"),"display"));
        wordsList.add(new DictionaryEntry(3,"profoundly", "/prəˈfaʊndli/", "To a profound extent; extremely.", "synonyms:\textremely, very, deeply, exceedingly, greatly, immensely", "\"a profoundly disturbing experience\"","معنی : به طور عمیق", "کد واژه : پروفسور!", "مثال : <font color='black'>پروفسور</font> ها <font color='red'>به طور عمیق </font>اطلاعاتشون زیاده!", R.drawable.profoundly,new TestEntry("deeply","relatively","emotionally","intensely"),"deeply"));
        wordsList.add(new DictionaryEntry(3,"sharpen", "/ˈʃɑːp(ə)n/", "Make or become sharp or sharper.", "synonyms:\tmake sharp/sharper, hone, whet, strop, grind, file", "\"she sharpened her pencil\"","معنی : تیز کردن", "کد واژه : شارپ!", "مثال : داشت چاقوش و <font color='red'>تیز</font> میکرد که <font color='black'>شارپ </font>خورد زمین!", R.drawable.sharpen,new TestEntry("convert","hone","focus","point"),"hone"));
        wordsList.add(new DictionaryEntry(3,"supervision", "/ˌsuːpəˈvɪʒn/", "The action of supervising someone or something.", "synonyms:\tadministration, management, direction, control, charge", "\"he was placed under the supervision of a probation officer\"","معنی : نظارت", "کد واژه : سوپر ویژه!", "مثال : روی این خیارشورای <font color='black'>سوپر ویژه </font>حسابی<font color='red'> نظارت شده</font>!", R.drawable.supervision,new TestEntry("control","polluted","confronted","crucial"),"control"));
        wordsList.add(new DictionaryEntry(3,"chunk", "/tʃʌŋk/", "A thick, solid piece of something.", "synonyms:\tlump, hunk, wedge, block, slab, square, nugget, nub", "\"huge chunks of masonry littered the street\"","معنی : کلفت", "کد واژه : چاک!", "مثال : این تکه <font color='red'> کلفت </font>درخت <font color='black'>چاک </font>خورده!", R.drawable.chunk,new TestEntry("exhibit","target","incorporate","piece"),"piece"));
        wordsList.add(new DictionaryEntry(3,"particular", "/pəˈtɪkjʊlə/", "Used to single out an individual member of a specified group or class.", "synonyms:\tspecific, certain, distinct, separate, isolated", "\"the action seems to discriminate against a particular group of companies\"","معنی : دقیق، خاص", "کد واژه : پارسی کولا!", "مثال : <font color='black'>پارسی کولا </font>مخصوص آدمهای <font color='red'> دقیقه</font>!", R.drawable.particular,new TestEntry("terrain","peer","specific","vital"),"specific"));
        wordsList.add(new DictionaryEntry(3,"feat", "/fēt/", "An achievement that requires great courage, skill, or strength.", "synonyms:\tachievement, accomplishment, attainment, coup,// triumph", "\"the new printing presses were considerable feats of engineering\"","معنی : شاهکار", "کد واژه : فیت (fit) !", "مثال : <font color='black'>فیت </font>شدن کار <font color='red'> شاهکاریه</font> !", R.drawable.feat,new TestEntry("patent","achievement","suitable","ancient"),"achievement"));
        wordsList.add(new DictionaryEntry(3,"hamper", "/ˈhampər/", "To make it difficult for someone to do something", "synonyms:\tbarricade, prevent, exclude, hinder, stop", "\"It hampers my business\"","معنی : مانع شدن", "کد واژه : پَنپِرز( پوشک pampers) !", "مثال : <font color='red'> مانع </font>ورود <font color='black'>پنپرز</font> به کشورمون شدن !", R.drawable.hamper,new TestEntry("basket","hone","sway","point"),"basket"));
        wordsList.add(new DictionaryEntry(3,"hone", "/hōn/", "A whetstone, especially one used to sharpen razors.", "synonyms:\tsharpen, whet, strop, grind, file; polish, refine, improve, enha//nce", "\"he was carefully honing the curved blade\"","معنی : با سنگ تیز کردن", "کد واژه : هان !!!", "مثال : <font color='black'>هان </font>!!! چاقو و<font color='red'> با سنگ تیز کردی </font>؟!!", R.drawable.hone,new TestEntry("sharpen","hamper","vital","disruptive"),"sharpen"));
        wordsList.add(new DictionaryEntry(3,"impact", "/ˈimˌpakt/", "The action of one object coming forcibly into contact with another.", "synonyms:\tcollision, crash, smash, bump, bang, knock", "\"there was the sound of a third impact\"","معنی : تأثیر داشتن", "کد واژه : این پاکت !", "مثال : <font color='black'>این پاکت </font><font color='red'>تأثیر </font>زیادی داره !", R.drawable.impact,new TestEntry("enrich","appeal","impose","effect"),"effect"));
        wordsList.add(new DictionaryEntry(3,"impose", "/ɪmˈpəʊz/", "Force (an unwelcome decision or ruling) on someone.", "synonyms:\tfoist, force, thrust, inflict, obtrude, press, urge", "\"the dec///ision was theirs and was not imposed on them by others\"","معنی : تحمیل کردن", "کد واژه : این پُز(دستگاه pose) !", "مثال : <font color='black'>این </font>دستگاه های <font color='black'>پُز </font>کلی خرج به ما <font color='red'>تحمیل میکنه </font>!", R.drawable.force,new TestEntry("impact","sway","pressure","suffer"),"pressure"));
        wordsList.add(new DictionaryEntry(3,"incapacitate", "/ˌinkəˈpasəˌtāt/", "Prevent from functioning in a normal way.", "synonyms:\tdisabled, debilitated, indisposed, unfit, impaired", "\"he was incapacitated by a heart attack\"","معنی : ناتوان کردن", "کد واژه : این کَپَک !", "مثال : <font color='black'>این کَپَک </font>خطرناک آدم و <font color='red'>ناتوان میکنه</font> !", R.drawable.incapacitate,new TestEntry("indicate","disabled","influence","inhabit"),"disabled"));
        wordsList.add(new DictionaryEntry(3,"incorporate", "/inˈkôrpəˌrāt/", "Take in or contain (something) as part of a whole; include.", "synonyms:\tabsorb, include, subsume, assimilate, integrate, take in", "\"he has incorporated in his proposals a large number of measures\"","معنی : ترکیب کردن", "کد واژه : این کار پُرِ !", "مثال : <font color='black'>این کار </font>پرِ از <font color='red'>ترکیب کردن </font>!", R.drawable.incorporate,new TestEntry("include","encourage","target","sharpen"),"include"));
        wordsList.add(new DictionaryEntry(3,"indicate", "/ˈindəˌkāt/", "Point out; show.", "synonyms:\tspecify, designate, mark, stipulate; show", "\"dotted lines indicate the text's margins\"","معنی : نشون دادن", "کد واژه : این دیکته !", "مثال : <font color='black'>این دیکته </font>خیلی چیزا به ما <font color='red'>نشون میده </font>!", R.drawable.indicate,new TestEntry("show","transmit","enrich","alter"),"show"));
        wordsList.add(new DictionaryEntry(3,"influence", "/ˈinflo͝oəns/", "The capacity to have an effect on the character, development, or behavior of someone or something, or the effect itself.", "synonyms:\teffect, impact; control, sway, hold, power, authority, mastery, domination, supremacy", "\"the influence of television violence\"","معنی : تأثیر گذاشتن", "کد واژه : آنفولانزا !", "مثال : <font color='black'>آنفولانزا </font><font color='red'>تأثیر </font>بدی رو آدم داره !", R.drawable.influence,new TestEntry("sharpen","effect","feat","impose"),"effect"));
        wordsList.add(new DictionaryEntry(3,"inhabit", "/inˈhabət/", "(of a person, animal, or group) Live in or occupy (a place or environment).", "synonyms:\tlive in/on, occupy, settle in/on, populate, colonize, dwell in/on", "\"a bird that inhabits North America\"","معنی : سکونت داشتن", "کد واژه : این habit !", "مثال : با <font color='black'>این habit </font>سالها اینجا <font color='red'>ساکن بودن </font>!", R.drawable.inhabit,new TestEntry("exhibit","incapacitate","occupy","indicate"),"occupy"));
        wordsList.add(new DictionaryEntry(3,"suffer", "/ˈsʌfə/", "Experience or be subjected to (something bad or unpleasant).", "synonyms:\thurt, ache, be in pain, feel pain, be racked with pain, endure agony, agonize", "\"he suffered intense pain\"","معنی : درد کشیدن", "کد واژه : سفر !", "مثال : تو این <font color='black'>سفر </font>حسابی <font color='red'>درد </font>کشیدم !", R.drawable.suffer,new TestEntry("undergo","impact","hamper","hurt"),"hurt"));
        wordsList.add(new DictionaryEntry(3,"suitable", "/ˈsuːtəb(ə)l/", "Right or appropriate for a particular person, purpose, or situation.", "synonyms:\tacceptable, satisfactory, fit, worthy, fitting", "\"these toys are not suitable for children under five\"","معنی : مناسب", "کد واژه : سو + table !", "مثال : اگر از این <font color='black'>سو میز (table) </font> و بذاری <font color='red'>مناسب</font> به نظر میاد !", R.drawable.suitable,new TestEntry("appropriate","supervision","reluctant","vital"),"appropriate"));
        wordsList.add(new DictionaryEntry(3,"sway", "/sweɪ/", "Move or cause to move slowly or rhythmically backwards and forwards or from side to side", "synonyms:\tswing, shake, oscillate, rock, undulate, move from side to side, move to and fro", "\"he swayed slightly on his feet\"","معنی : نوسان", "کد واژه : s + way !", "مثال : در این<font color='black'> راه</font> (way) دچار <font color='red'>نوسان </font>شدن !", R.drawable.sway,new TestEntry("peer","fluctuate","sharpen","impact"),"fluctuate"));
        wordsList.add(new DictionaryEntry(3,"target", "/ˈtɑːɡɪt/", "A person, object, or place selected as the aim of an attack.", "synonyms:\tmark, bullseye, goal, aim", "\"the car met its sales target in record time\"","معنی : هدف", "کد واژه : تار + get !", "مثال : این <font color='black'>تار</font> و بگیر<font color='black'> (get) </font>  و <font color='red'>هدف </font>خودت قرار بده !", R.drawable.target,new TestEntry("hone","hamper","goal","feat"),"goal"));
        wordsList.add(new DictionaryEntry(3,"terrain", "/tɛˈreɪn/", "A stretch of land, especially with regard to its physical features.", "synonyms:\tland, ground, territory", "\"they were delayed by rough terrain\"","معنی : زمینی", "کد واژه : train !", "مثال : این<font color='black'> train </font>یه قطار <font color='red'>زمینی</font> است !", R.drawable.terrain,new TestEntry("chunk","vital","thirst","territory"),"territory"));
        wordsList.add(new DictionaryEntry(3,"thirst", "/θəːst/", "A feeling of needing or wanting to drink something.", "synonyms:\tthirstiness, dryness; dehydration", "\"they quenched their thirst with spring water\"","معنی : تشنگی", "کد واژه : ترس !", "مثال : از روی <font color='black'> ترس </font>دچار <font color='red'>تشنگی </font>شدم !", R.drawable.thirst,new TestEntry("dryness","chunk","feat","patent"),"dryness"));
        wordsList.add(new DictionaryEntry(3,"transfer", "/transˈfə/", "Move from one place to another", "synonyms:\tmove, convey, shift, remove, take, carry, fetch, lift, bring, bear", "\"he intends to transfer the fund's assets to the Treasury\"","معنی : جابه جا کردن", "کد واژه : trans(همیشه به معنی از سویی یا شکلی به سو یا شکلی دیگر است) + فر !", "مثال : این <font color='black'>فر</font> رو از اینجا به اونجا<font color='red'> جابه جا کردن</font>!", R.drawable.transfer,new TestEntry("incapacitate","shift","sway","undergo"),"shift"));
        wordsList.add(new DictionaryEntry(3,"transmit", "/tranzˈmɪt/", "Cause (something) to pass on from one person or place to another.", "synonyms:\ttransfer, pass on, hand on, communicate, convey, impart", "\"knowledge is transmitted from teacher to pupil\"","معنی : منتقل کردن", "کد واژه : trans(همیشه به معنی از سویی یا شکلی به سو یا شکلی دیگر است) + meet !", "مثال : توی <font color='black'>ملاقاتی </font>که داشتیم من و از این سِمَت به سِمَت دیگه <font color='red'>انتقال دادن </font>!", R.drawable.transmit,new TestEntry("suffer","exhibit","transfer","incorporate"),"transfer"));
        wordsList.add(new DictionaryEntry(3,"undergo", "/ʌndəˈɡəʊ/", "Experience or be subjected to (something, typically something unpleasant or arduous).", "synonyms:\tgo through, experience, engage in, undertake, live through, face, encounter", "\"he underwent a life-saving brain operation\"","معنی : تحمل کردن", "کد واژه : under + go !", "مثال : <font color='black'>زیر</font> این <font color='black'>رفت </font>و آمد ها خیلی چیز ها رو<font color='red'> تحمل کردم </font>!", R.drawable.undergo,new TestEntry("impose","observe","dire","experience,"),"experience"));
        wordsList.add(new DictionaryEntry(3,"validate", "/ˈvalɪdeɪt/", "Check or prove the validity or accuracy of.", "synonyms:\tprove, give proof of, show to be true, give substance to", "\"all analytical methods should be validated in respect of accuracy\"","معنی : معتبر کردن",  "کد واژه : ولی + date !",  "مثال : <font color='black'>ولی</font> این تاریخ<font color='black'> (date) </font>و نمیشه <font color='red'>معتبر </font>و قانونی دونست !", R.drawable.validate,new TestEntry("prove","influence","appeal","sparse"),"prove"));
        wordsList.add(new DictionaryEntry(4,"boundary", "/ˈbound(ə)rē/", "A line that marks the limits of an area; a dividing line.", "synonyms:\tborder, frontier, borderline, partition", "\"the eastern boundary of the wilderness\"", "معنی : مرز", "کد واژه : بندری!", "مثال : تا حالا تو <font color='black'>مرز </font><font color='red'>بندری</font> خوردی ؟", R.drawable.boundary,new TestEntry("border","closure","abroad","edge"),"border"));
        wordsList.add(new DictionaryEntry(4,"chronic", "/ˈkränik/", "(of an illness) Persisting for a long time or constantly recurring.", "synonyms:\tpersistent, long-standing, long-term", "\"chronic bronchitis\"", "معنی : قدیمی و مزمن", "کد واژه : کارون !", "مثال : رودخانه<font color='black'> کارون </font>از رودخانه های <font color='red'>کهن </font>این دیار است!", R.drawable.chronic,new TestEntry("ancient","lasting","awful","habitual"),"lasting" ));
        wordsList.add(new DictionaryEntry(4,"coarse", "/kôrs/", "1. Rough or loose in texture or grain.\n2. (of a person or their speech) Rude, crude, or vulgar.", "synonyms:\trough, scratchy, prickly, wiry, oafish, loutish, boorish, uncouth, rude, impolite, ill-mannered, uncivil", "\"a coarse woolen cloth\"", "معنی : بی ادب، مبتذل", "کد واژه : کورس!", "مثال : بعضی از این نوجونای امروزی هم که تو<font color='red'> بی ادبی </font>با هم <font color='black'> کورس </font>گذاشتن.", R.drawable.coarse,new TestEntry("validate","vast","rough","lack"),"rough" ));
        wordsList.add(new DictionaryEntry(4,"compete", "/kəmˈpēt/", "Strive to gain or win something by defeating or establishing superiority over others who are trying to do the same.", "synonyms:\ttake part, participate, play, be a competitor, be involved, rival, challenge, keep up with, keep pace with, compare with", "\"universities are competing for applicants\"", "معنی : رقابت داشتن", "کد واژه: کمپوت!", "مثال : این<font color='black'>  کمپوت ها </font>سر خوشمزگی با هم <font color='red'>رقابت دارن</font>!", R.drawable.compete,new TestEntry("impact","rally","plead","contest"),"contest" ));
        wordsList.add(new DictionaryEntry(4,"culprit", "/ˈkəlprət/", "A person who is responsible for a crime or other misdeed.", "synonyms:\tguilty party, offender, wrongdoer, perpetrator, miscreant", "\"viruses could turn out to be the culprit\"", "معنی : مجرم", "کد واژه : کل پیرا!", "مثال : <font color='black'>  کل پیرا </font>رو هم جمع کنی از پس این<font color='red'> مجرم </font>بر نمیان!", R.drawable.culprit,new TestEntry("criminal","patent","ancient","tricky"),"criminal" ));
        wordsList.add(new DictionaryEntry(4,"delicate", "/ˈdelikət/", "1. Very fine in texture or structure; of intricate workmanship or quality.\n2. Easily broken or damaged; fragile.\n3. Requiring sensitive or careful handling.", "synonyms:\tfine, exquisite, intricate, dainty, fragile, breakable, frail, difficult, tricky, sensitive, ticklish, awkward, problematic", "\"a spider's web, strong yet delicate\"\n\"delicate china\"\n\"delicate negotiations\"", "معنی : دقیق و حساس", "کد واژه :(کار) دلی !", "مثال : بخوای<font color='black'>  کار دلی </font>کنی باید<font color='red'> دقیق و حساس</font> باشی!", R.drawable.delicate,new TestEntry("energetic","phenomena","elegant","marvel"),"elegant" ));
        wordsList.add(new DictionaryEntry(4,"endeavour", "/ɪnˈdɛvə,ɛnˈdɛvə/", "Try hard to do or achieve something.", "synonyms:\ttry, attempt, venture, undertake, aspire, aim, seek", "\"he is endeavouring to help the Third World\"", "معنی : تلاش کردن", "کد واژه : این دیوار!", "مثال : رو<font color='black'>  این دیوار</font>نوشته<font color='red'> تلاش کن</font> !", R.drawable.endeavour,new TestEntry("impose","commit","breed","attempt"),"attempt" ));
        wordsList.add(new DictionaryEntry(4,"endure", "/ɪnˈdjʊə/", "1. Suffer (something painful or difficult) patiently.\n2. remain in existence; last.", "synonyms:\tundergo, go through, live through, experience, meet, encounter", "\"it seemed impossible that anyone could endure such pain\"", "معنی : تحمل کردن", "کد واژه : این دیار!", "مثال : <font color='black'> این دیار</font> دیگه سخت شده برای <font color='red'>تحمل کردن</font>!", R.drawable.endure,new TestEntry("tolerate","attempt","lure","outcome"),"tolerate" ));
        wordsList.add(new DictionaryEntry(4,"enhance", "/ɪnˈhɑːns/", "Intensify, increase, or further improve the quality, value, or extent of.", "synonyms:\tincrease, add to, intensify, magnify, amplify, inflate, strengthen, build up, supplement", "\"his refusal does nothing to enhance his reputation\"", "معنی : بالا بردن", "کد واژه : این هانس!", "مثال : <font color='black'> این هانس</font> و گریتل هم توقعات ما رو<font color='red'> بالا بردن</font>!", R.drawable.enhance,new TestEntry("quash","transmit","undergo","descend"),"increase" ));
        wordsList.add(new DictionaryEntry(4,"file", "/fʌɪl/", "1. A folder or box for holding loose papers together and in order for easy reference.\n2. Place (a document) in a cabinet, box, or folder in a particular order.", "synonyms:\tfolder, portfolio, binder, box, document case; filing cabinet", "\"a file of correspondence\"\n\"the contract, when signed, is filed\"", "معنی : دسته بندی کردن", "کد واژه : فایل!", "مثال : این <font color='black'> فیله  </font>ها رو <font color='red'>دسته بندی کن</font>!", R.drawable.file,new TestEntry("afloat","folder","span","record"),"folder" ));
        wordsList.add(new DictionaryEntry(4,"span", "/span/", "The full extent of something from end to end; the amount of space that something covers.", "synonyms:\t(full) extent, length, width, reach, stretch, spread, distance, compass", "\"a warehouse with a clear span of 28 feet\"","معنی : یک وجب، ظرفیت", "کد واژه : اسپانیا!", "مثال : <font color='red'> ظرفیت </font> کشور<font color='black'> اسپانیا </font> به قدری زیاده که اندازه <font color='red'> یک وجب </font>دست هم کم میاد واسه اندازه گیریش توی نقشه!", R.drawable.span,new TestEntry("validate","distort","measure","indicate"),"measure" ));
        wordsList.add(new DictionaryEntry(4,"marvel", "/ˈmɑːv(ə)l/", "Be filled with wonder or astonishment.", "synonyms:\tbe amazed, be filled with amazement, be astonished, be surprised", "\"she marvelled at Geoffrey's composure\"","معنی : معجزه", "کد واژه : مارِ ول!", "مثال : همین که اون <font color='black'>مارِ ول</font> طرف و نیش نزد یه<font color='red'> معجزست</font>!", R.drawable.marvel,new TestEntry("endure","sway","express","wonder"),"wonder"));
        wordsList.add(new DictionaryEntry(4,"toxic", "/ˈtɒksɪk/", "Poisonous.", "synonyms:\tpoisonous, venomous, virulent, noxious, dangerous, destructive, harmful", "\"the dumping of toxic waste\"","معنی : سمی", "کد واژه : تاکسی!", "مثال : بیچاره تو <font color='black'>تاکسی </font> <font color='red'>سمی شده</font>!", R.drawable.toxic,new TestEntry("poisonous","tricky","markedly","massive"),"poisonous"));
        wordsList.add(new DictionaryEntry(4,"vast", "/vɑːst/", "Of very great extent or quantity; immense.", "synonyms:\thuge, extensive, expansive, broad, wide, boundless, immeasurable, limitless, infinite, enormous, gigantic, very big, very large, great, giant, massive", "\"a vast plain full of orchards\"","معنی : پهناور", "کد واژه : وسط!", "مثال : هرچیزی داری بریز<font color='black'> وسط </font> ببین چه چیز <font color='red'>پهناور </font>و عظیمی بشه!", R.drawable.vast,new TestEntry("outperformed","huge","huddle","reached"),"huge"));
        wordsList.add(new DictionaryEntry(4,"convince", "/kənˈvɪns/", "Cause (someone) to believe firmly in the truth of something.\nPersuade (someone) to do something.", "synonyms:\tpersuade, satisfy, prove to, cause to feel certain", "\"Robert's expression had obviously convinced her of his innocence\"\n\"she convinced my father to branch out on his own\"","معنی : قانع کردن", "کد واژه : کن ونوس رو قانع!", "مثال : <font color='black'>ونوس </font>و <font color='red'>قانع کن</font>!", R.drawable.convince,new TestEntry("meander","hamper","persuade","believe"),"persuade"));
        wordsList.add(new DictionaryEntry(4,"product", "/ˈprɒdʌkt/", "An article or substance that is manufactured or refined for sale.\nA thing or person that is the result of an action or process.", "synonyms:\tartifact, commodity, manufactured item/article/thing,result, consequence, outcome, effect, upshot, fruit, by-product, spin-off, legacy", "\"food products\"\n\"her perpetual suntan was the product of a solarium\"","معنی : محصول", "کد واژه : پر دکتر!", "مثال : در محل ارائه این<font color='red'> محصول</font> <font color='black'>پر دکتره</font>!", R.drawable.product,new TestEntry("outperformed","distort","process","outcome"),"outcome"));
        wordsList.add(new DictionaryEntry(4,"acknowledge", "/əkˈnɒlɪdʒ/", "Accept or admit the existence or truth of.", "synonyms:\tadmit, accept, grant, allow, concede, confess, own, appreciate", "\"the plight of the refugees was acknowledged by the authorities\"","معنی : اعتراف کردن", "کد واژه : knowledge !", "مثال : <font color='red'>اعتراف کرد </font> که به اندازه ی کافی<font color='black'> knowledge </font>نداره!", R.drawable.acknowledge,new TestEntry("admit","compete","claim","validate"),"admit"));
        wordsList.add(new DictionaryEntry(4,"afloat", "/əˈfləʊt/", "Floating in water; not sinking.", "synonyms:\tbuoyant, floating, buoyed up, non-submerged, suspended", "\"they trod water to keep afloat\"","معنی : شناور", "کد واژه : همون float !", "معنی float رو میده یعنی <font color='red'>شناور</font>!", R.drawable.afloat,new TestEntry("floating","marvel","delicate","reign"),"floating"));
        wordsList.add(new DictionaryEntry(4,"apparently", "/əˈparəntli/", "As far as one knows or can see.", "synonyms:\tseemingly, evidently, it seems (that), it would seem (that), it appears (that)", "\"the child nodded, apparently content with the promise\"","معنی : ظاهراً", "کد واژه : parent !", "مثال : <font color='red'>ظاهراً </font> اینا<font color='black'> parent  </font>هستن!", R.drawable.apparently,new TestEntry("markedly","evidently","chronic","vast"),"evidently"));
        wordsList.add(new DictionaryEntry(4,"array", "/əˈreɪ/", "Display or arrange (things) in a particular way.", "synonyms:\tarrange, assemble, draw up, group, order, range", "\"the manifesto immediately divided the forces arrayed against him\"","معنی : چیدمان", "کد واژه : اره!", "مثال : <font color='red'>چیدمان </font>این <font color='black'>اره </font>ها کار سختیه !", R.drawable.array,new TestEntry("span","toxic","arrangement","mentor"),"arrangement"));
        wordsList.add(new DictionaryEntry(4,"lure", "/lo͝or/", "Tempt (a person or an animal) to do something or to go somewhere, especially by offering some form of reward.", "synonyms:\ttempt, entice, attract, induce, coax, persuade, inveigle, allure, seduce, win over", "\"the child was lured into a car but managed to escape\"","معنی : وسوسه شدن", "کد واژه : لُر !", "مثال : <font color='black'>لُر </font>ها دچار <font color='red'>وسوسه شدن </font>!", R.drawable.lure,new TestEntry("enhance","coarse","rally","tempt"),"tempt"));
        wordsList.add(new DictionaryEntry(4,"mandate", "/ˈmanˌdāt/", "An official order or commission to do something.", "synonyms:\tinstruction, directive, decree, command, order, injunction", "\"a mandate to seek the release of political prisoners\"","معنی : فرمان", "کد واژه : man + date !", "مثال : به این <font color='black'>مرد </font>در این <font color='black'>تاریخ </font><font color='red'>فرمان </font>داده شد !", R.drawable.mandate,new TestEntry("instruction","massive","culprit","file"),"instruction"));
        wordsList.add(new DictionaryEntry(4,"markedly", "/ˈmärkədlē/", "To an extent that is clearly noticeable; significantly.", "\"new diagnoses have increased markedly since 1998\"","", "معنی : به طور محسوس", "کد واژه : mark !", "مثال : اینجا <font color='red'>به طور محسوس </font>پر از<font color='black'> نشان </font>است !", R.drawable.markedly,new TestEntry("noticeably","relatively","accessible","crucial"),"noticeably"));
        wordsList.add(new DictionaryEntry(4,"massive", "/ˈmasiv/", "Large and heavy or solid.", "synonyms:\thuge, enormous, vast, immense, large, big, mighty, great, colossal, tremendous", "\"a massive rampart of stone\"","معنی : به صورت گسترده", "کد واژه : مِسی !", "مثال : <font color='black'>مِسی </font>به <font color='red'>صورت گسترده ای </font>با استعداده !", R.drawable.massive,new TestEntry("boundary","huge","span","terrain"),"huge"));
        wordsList.add(new DictionaryEntry(4,"mentor", "/ˈmenˌtôr/", "An experienced and trusted adviser.", "synonyms:\tadviser, guide, guru, counselor, consultant", "\"he was her friend and mentor until his death in 1915\"","معنی : مربی", "کد واژه : مانتو!", "مثال  : <font color='red'>مربی </font>ما <font color='black'>مانتو </font>میپوشه !", R.drawable.mentor,new TestEntry("tenant","huddle","adviser","asylum"),"adviser"));
        wordsList.add(new DictionaryEntry(4,"outcome", "/ˈoutˌkəm/", "the way a thing turns out; a consequence.", "synonyms:\tresult, end result, consequence, net result, upshot, aftereffect, aftermath, conclusion", "\"it is the outcome of the vote that counts\"","معنی : نتیجه", "کد واژه : out + come !", "مثال : از<font color='black'> بیرون </font>که <font color='black'>بیای </font><font color='red'>نتیجش </font>همین میشه ! ", R.drawable.outcome,new TestEntry("passion","afloat","array","result"),"result"));
        wordsList.add(new DictionaryEntry(4,"outperform", "/ˌoutpərˈfôrm/", "Perform better than.", "(of an investment) Be more profitable than.", "\"an experienced employee will outperform the novice\"","معنی : پیشی گرفتن", "کد واژه : out + perform !", "مثال : از <font color='black'>بیرون </font>یه کارایی <font color='black'>انجام دادن</font> و از همه<font color='red'> پیشی گرفتن</font>!", R.drawable.outperform,new TestEntry("perform better","acknowledge","commit","distort"),"perform better"));
        wordsList.add(new DictionaryEntry(4,"passion", "/ˈpaSHən/", "Strong and barely controllable emotion.", "synonyms:\tfervor, ardor, enthusiasm, eagerness, zeal, zealousness, vigor, fire, fieriness", "\"the English have a passion for gardens\"","معنی : هیجان", "کد واژه : پاشو !", "مثال : <font color='black'>پاشو </font>از خودت شور و <font color='red'>هیجان </font>نشون بده !", R.drawable.passion,new TestEntry("temper","chronic","product","reluctant"),"temper"));
        wordsList.add(new DictionaryEntry(4,"rally", "/ˈralē/", "(of troops) Come together again in order to continue fighting after a defeat or dispersion.", "synonyms:\tregroup, reassemble, re-form, reunite", "\"De Montfort's troops rallied and drove back the king's infantry\"","معنی : سروسامان دادن", "کد واژه : رالی !", "مثال : جدیداً مسابقات<font color='black'> رالی </font>و خیلی <font color='red'>سرو سامون دادن </font>!", R.drawable.rally,new TestEntry("lure","reassemble","marvel","endeavour"),"reassemble"));
        wordsList.add(new DictionaryEntry(4,"reign", "/reɪn/", "Hold royal office; rule as monarch.", "synonyms:\tbe king/queen, be monarch, be sovereign, sit on the throne, occupy the throne", "\"Queen Elizabeth reigns over the UK\"","معنی : حکمرانی کردن", "کد واژه : راین (اسم پسرونه) !", "مثال : این <font color='black'>راین </font>هم که تو خونه همش به همه <font color='red'>حکمفرمانی </font>میکنه!", R.drawable.reign,new TestEntry("contribute","quash","govern","convince"),"govern"));
        wordsList.add(new DictionaryEntry(4,"jury", "/ˈdʒʊəri/", "A body of people (typically twelve in number) sworn to give a verdict in a legal case on the basis of evidence submitted to them in court.", "\"the jury returned unanimous guilty verdicts\"", "","معنی : هیئت منصفه دادگاه", "کد واژه : جِری (تام و جِری) !", "مثال : اگه یه دادگاه بر تام و<font color='black'> جری</font> میذاشتن حتماً جِری و <font color='red'>ا هیئت منصفه دادگاه </font>محکوم میکرد !", R.drawable.jury,new TestEntry("asylum","passion","mentor","judge "),"judge "));
        wordsList.add(new DictionaryEntry(4,"commit", "/kəˈmɪt/", "Perpetrate or carry out (a mistake, crime, or immoral act).", "synonyms:\tcarry out, do, perform, perpetrate, engage in, enact, execute, effect", "\"he committed an uncharacteristic error\"","معنی : انجام دادن", "کد واژه : come + it !", "مثال : بیا <font color='black'> (come) </font> و این کار رو <font color='red'>انجام بده</font>!", R.drawable.commit,new TestEntry("perform","plead","outperform","meander"),"perform"));
        wordsList.add(new DictionaryEntry(4,"plead", "/pliːd/", "Make an emotional appeal.\nPresent and argue for (a position), especially in court or in another public context.", "synonyms:\tbeg, entreat, beseech, implore, claim, use as an excuse, assert", "\"she pleaded with them not to gag the boy\"\n\"the idea that in public relations work someone is paid to plead a special case is disliked\"","معنی : التماس", "کد واژه : پَلید !", "مثال : برای اون آدم<font color='black'> پَلید </font><font color='red'> التماس </font>نکن!", R.drawable.plead,new TestEntry("argue","request","address","defend"),"request"));
        wordsList.add(new DictionaryEntry(4,"asylum", "/əˈsʌɪləm/", "The protection granted by a state to someone who has left their home country as a political refugee.", "synonyms:\trefuge, sanctuary, shelter, safety, safe keeping, protection, security", "\"she applied for asylum and was granted refugee status\"","معنی : پناهگاه", "کد واژه : اسیر !", "مثال : این <font color='black'>اسیر</font>ها رو تو <font color='red'>پناهگاه </font>نگه میدارن !", R.drawable.asylum,new TestEntry("accomodation","homeless","shelter","condition"),"shelter"));
        wordsList.add(new DictionaryEntry(4,"distort", "/dɪˈstɔːt/", "Pull or twist out of shape.", "synonyms:\ttwist, warp, contort, bend, buckle, deform, malform", "\"a grimace distorted her fine mouth\"","معنی : از ریخت افتادن", "کد واژه : دیس ِتارت (یه نوع شیرینی) !", "مثال : چرا این <font color='black'>دیس تارت </font><font color='red'>از ریخت افتاده </font>؟", R.drawable.distort,new TestEntry("sway","provide","mislead","deform"),"deform"));
        wordsList.add(new DictionaryEntry(4,"huddle", "/ˈhʌd(ə)l/", "Crowd together; nestle closely.", "synonyms:\tcrowd, gather, throng, flock, herd, pile, bunch, cluster", "\"they huddled together for warmth\"","معنی : ازدحام", "کد واژه : عادل (فردوسی پور) !", "مثال : <font color='black'>عادل </font>از<font color='red'> ازدحام </font>مردم گزارش میداد !", R.drawable.huddle,new TestEntry("crowd","tenant","vast","massive"),"crowd"));
        wordsList.add(new DictionaryEntry(4,"contribute", "/kənˈtrɪbjuːt/", "give (something, especially money) in order to help achieve or provide something.", "synonyms:\tgive, donate, give/make a donation of, put up, come up with", "\"taxpayers had contributed £141.8 million towards the cost of local services\"","معنی : شرکت کردن", "کد واژه : country +  bute !", "مثال : کل <font color='black'>کشور (country) </font>در این برنامه <font color='red'>شرکت کردن</font> !", R.drawable.contribute,new TestEntry("rally","lure","meander","give"),"give"));
        wordsList.add(new DictionaryEntry(4,"tenant", "/ˈtɛnənt/", "A person who occupies land or property rented from a landlord.", "synonyms:\toccupant, resident, inhabitant", "\"council-house tenants\"","معنی : اجاره", "کد واژه : ten + ants (10 تا مورچه) ! ", "مثال : با<font color='black'> 10 تا مورچه </font>خونه رو<font color='red'> اجاره </font> کردن !", R.drawable.tenant,new TestEntry("occupant","landlord","owner","resident"),"occupant"));
        wordsList.add(new DictionaryEntry(4,"meander", "/mɪˈandə/", "(of a river or road) Follow a winding course.", "synonyms:\tzigzag, wind, twist, turn, curve, curl, bend, snake", "\"a river that meandered gently through a meadow\"","معنی : مسیر پیچیده", "کد واژه : me + and (می اند)!", "مثال : <font color='black'> من و تو </font><font color='red'>مسیر پیچیده ای و طی کردیم</font> !", R.drawable.meander,new TestEntry("walk","stroll","exercise","stretch"),"stroll"));
        wordsList.add(new DictionaryEntry(4,"quash", "/kwɒʃ/", "Reject as invalid, especially by legal procedure.", "synonyms:\tcancel, reverse, rescind, repeal, revoke, retract, countermand, withdraw, take back, rule against, disallow, overturn, override, overrule", "\"his conviction was quashed on appeal\"","معنی : باطل", "کد واژه : گواش !", "مثال : اعتبار این <font color='black'>گواش </font><font color='red'>باطل </font>شده !", R.drawable.invalidate,new TestEntry("negotiate","prove","disprove","convert"),"disprove"));
    }

    public static ArrayList<DictionaryEntry> getAllEntries(int lessonLevel) {

        ArrayList<DictionaryEntry> sample = new ArrayList<>();

        for (DictionaryEntry entry : wordsList) {

            if (entry.getLessonNumber() == lessonLevel) {

                sample.add(entry);
            }
        }
        return sample;
    }

    public static DictionaryEntry getDefinition(String word) {

        for (DictionaryEntry entry : wordsList) {
            if (entry.getWord().equals(word)) {
                return entry;
            }
        }

        return null;

    }
    public static ArrayList<DictionaryEntry> getAllEntries() {

        ArrayList<DictionaryEntry> sample = new ArrayList<>();

        for (DictionaryEntry entry : wordsList) {

                sample.add(entry);

        }
        return sample;
    }


}